services:
    OpenDxp\Bundle\NewsletterBundle\Messenger\Handler\SendNewsletterHandler:
        arguments:
            - '%opendxp_newsletter%'
            - '@opendxp_newsletter.address_source_adapter.factories'
        tags:
            - { name: messenger.message_handler }
